### ISSUE TITLE
Proposal: Moving from clap to structopt

### ISSUE THREAD

**Issue by barskern** [greyblake/cargo-testify#10]
Since this library is using [clap](https://github.com/clap-rs/clap) directly, the definition of the arguments and subcommands is IMO verbose. Further one has to manually convert the hashmap of arguments into their respective types. Hence I was thinking about rewriting the CLI relevant code to rather use [structopt](https://github.com/TeXitoi/structopt) instead.

**Before doing this I was wondering if this is something that you see as relevant, or if it is a reason behind using clap directly?**

------

> structopt - This crate allows you to define a struct, and build a CLI from it! No more "stringly typed" and it uses clap behind the scenes! (Note: There is work underway to pull this crate into mainline clap).
> -- README.md of clap

There is a process ongoing which will make the structopt-way of defining arguments possible directly in clap, hence it seems as though the community is moving towards a singular way of defining arguments. When this change happens, it will probably be easy to migrate back to clap, using the new structopt code.

**Comment by greyblake** [comment]
@barskern Hey :)

Thanks for contacting me.
Honestly I haven't heard about structopt, but it looks like it's something that I often happened to do myself: parse command line arguments into some kind of Config struct.
I even implemented recently something very similar, but much simpler, to init Config from env variables: https://github.com/greyblake/envconfig-rs

So thanks for pointing me to structopt, it looks cool, and I would probably try to use it next time.

Regarding rewriting to use this crate to use structopt: I would not do it myself, just because I do not have time now. But if you're willing to have fun and contribute I would be happy to merge a pull request :)
